language: cpp

dist: xenial

before_install:
    - sudo add-apt-repository --yes ppa:beineri/opt-qt58-trusty
    - sudo apt-get -qq update

install:
    - sudo apt-get --yes install qt58base

before_script:
    - QTDIR="/opt/qt58"
    - PATH="$QTDIR/bin:$PATH"
    - source /opt/qt58/bin/qt58-env.sh

