language: cpp
compiler: gcc
sudo: require
dist: trusty

before_install:
    - sudo add-apt-repository ppa:beineri/opt-qt58-trusty -y
    - sudo apt-get update -qq
    
install: 
    - sudo apt-get -y install qt58base
    - source /opt/qt58/bin/qt58-env.sh

script:
  - qmake PREFIX=/usr
  - make -j4
  - sudo apt-get -y install checkinstall
  - sudo checkinstall --pkgname=app --pkgversion="1" --pkgrelease="1" --backup=no --fstrans=no --default --deldoc 
  - mkdir appdir ; cd appdir
  - dpkg -x ../app_1-1_amd64.deb . ; find .
#  - cp ./usr/share/applications/*.desktop .
#  - cp ./usr/share/icons/hicolor/48x48/apps/*.png  - cd ..
